export const NEW_GAME_ACTION = 'NEW_GAME_ACTION';
export const SELECT_HUMAN_SYMBOL_ACTION = 'SELECT_HUMAN_SYMBOL_ACTION';
export const MOVE_ACTION = 'MOVE_ACTION';
export const UNDO_ACTION = 'UNDO_ACTION';
export const REDO_ACTION = 'REDO_ACTION';
